//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 10:11:07 PM CDT 
//


package com.san.nyc.taxidata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.san.nyc.taxidata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.san.nyc.taxidata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListBucketResult }
     * 
     */
    public ListBucketResult createListBucketResult() {
        return new ListBucketResult();
    }

    /**
     * Create an instance of {@link ListBucketResult.Contents }
     * 
     */
    public ListBucketResult.Contents createListBucketResultContents() {
        return new ListBucketResult.Contents();
    }

    /**
     * Create an instance of {@link ListBucketResult.Contents.Owner }
     * 
     */
    public ListBucketResult.Contents.Owner createListBucketResultContentsOwner() {
        return new ListBucketResult.Contents.Owner();
    }

}
